# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_base_pb2 as trading__base__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_base_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingBaseStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/trading_base.TradingBase/Register',
                request_serializer=trading__base__pb2.StrategyConfig.SerializeToString,
                response_deserializer=trading__base__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/trading_base.TradingBase/Unregister',
                request_serializer=trading__base__pb2.StrategyId.SerializeToString,
                response_deserializer=trading__base__pb2.UnregisterAck.FromString,
                _registered_method=True)
        self.SubscribeBars = channel.unary_stream(
                '/trading_base.TradingBase/SubscribeBars',
                request_serializer=trading__base__pb2.BarRequest.SerializeToString,
                response_deserializer=trading__base__pb2.Bar.FromString,
                _registered_method=True)
        self.SubmitSignal = channel.unary_unary(
                '/trading_base.TradingBase/SubmitSignal',
                request_serializer=trading__base__pb2.Signal.SerializeToString,
                response_deserializer=trading__base__pb2.SignalAck.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/trading_base.TradingBase/GetState',
                request_serializer=trading__base__pb2.StateRequest.SerializeToString,
                response_deserializer=trading__base__pb2.StateResponse.FromString,
                _registered_method=True)
        self.ClosePosition = channel.unary_unary(
                '/trading_base.TradingBase/ClosePosition',
                request_serializer=trading__base__pb2.CloseRequest.SerializeToString,
                response_deserializer=trading__base__pb2.CloseAck.FromString,
                _registered_method=True)


class TradingBaseServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClosePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingBaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=trading__base__pb2.StrategyConfig.FromString,
                    response_serializer=trading__base__pb2.RegisterAck.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=trading__base__pb2.StrategyId.FromString,
                    response_serializer=trading__base__pb2.UnregisterAck.SerializeToString,
            ),
            'SubscribeBars': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBars,
                    request_deserializer=trading__base__pb2.BarRequest.FromString,
                    response_serializer=trading__base__pb2.Bar.SerializeToString,
            ),
            'SubmitSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSignal,
                    request_deserializer=trading__base__pb2.Signal.FromString,
                    response_serializer=trading__base__pb2.SignalAck.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=trading__base__pb2.StateRequest.FromString,
                    response_serializer=trading__base__pb2.StateResponse.SerializeToString,
            ),
            'ClosePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ClosePosition,
                    request_deserializer=trading__base__pb2.CloseRequest.FromString,
                    response_serializer=trading__base__pb2.CloseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading_base.TradingBase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading_base.TradingBase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingBase:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_base.TradingBase/Register',
            trading__base__pb2.StrategyConfig.SerializeToString,
            trading__base__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_base.TradingBase/Unregister',
            trading__base__pb2.StrategyId.SerializeToString,
            trading__base__pb2.UnregisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trading_base.TradingBase/SubscribeBars',
            trading__base__pb2.BarRequest.SerializeToString,
            trading__base__pb2.Bar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_base.TradingBase/SubmitSignal',
            trading__base__pb2.Signal.SerializeToString,
            trading__base__pb2.SignalAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_base.TradingBase/GetState',
            trading__base__pb2.StateRequest.SerializeToString,
            trading__base__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClosePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_base.TradingBase/ClosePosition',
            trading__base__pb2.CloseRequest.SerializeToString,
            trading__base__pb2.CloseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
